server:
  port: 8083
  servlet:
    context-path: /api

spring:
  application:
    name: content-service
  datasource:
    url: jdbc:postgresql://localhost:5432/content_db
    username: admin
    password: admin_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true