apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: auth-service
          image: yny.ocir.io/axspvtyyqq6h/auth-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/auth_db
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin_password
            - name: JWT_SECRET
              value: local-dev-secret-key-for-jwt-must-be-32chars
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
