FROM gradle:8.5-jdk17 AS build
WORKDIR /app
COPY . .
RUN gradle :content-service:build -x test

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/content-service/build/libs/*.jar app.jar
EXPOSE 8083
ENTRYPOINT [ "java", "-jar", "app.jar" ]